job.name=CustomerSegmentation
job.class=com.paytm.map.features.datasets.CustomerSegmentation

job.nExecutors=60
job.executorMem=12g
job.executorCores=2

type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${groupPrefix}"
dependencies=CheckProfile
