job.name=G1CreateLocation
job.class=com.paytm.map.features.Chakki.CreateDataSet
job.nExecutors=50
job.executorMem=6g

type=command
levelPrefix=LOCATION
cacheTo=nocaching

command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${levelPrefix} ${groupPrefix} ${cacheTo}"
dependencies=G1CreateDevice