job.name=UpdateBetaoutHistoricals
job.class=com.paytm.map.features.campaigns.UpdateBetaoutHistoricals

job.nExecutors=20
job.executorMem=16g
job.memoryOverhead=4g
job.executorCores=1
noCsvs = 23
job.args="${noCsvs}"

type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries}  --optArgs ${job.args}