job.name=RechargePredictionExportForEngage
job.class=com.paytm.map.featuresplus.rechargeprediction.ExportForEngage

dependencies=RegressorScoring
type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries}

