job.name=RechargePredictionFeaturesScoring
job.class=com.paytm.map.featuresplus.rechargeprediction.Features
job.flow=scoring

dependencies=BaseTable
type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${job.flow}"
