python_tests(
  dependencies = [
    'lambda/src/python/paytm/job',
    'lambda/src/python/paytm/async_result',
    'lambda/test/python/paytm/job:test-lib'
  ],
  tags = ['integration', 'dynamodb']
)
