job.name=CheckLatestAvlDateRawDatasets
job.class=com.paytm.map.features.sanity.CheckRawDatasetFreshness

job.nExecutors=3
job.executorMem=2g
job.executorCores=4
job.driverMem=2g

type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries}
dependencies=SendEmailFeatSanityReport