job.name=AggFeaturesGARaw
job.class=com.paytm.map.features.base.AggFeaturesGARaw

job.executorMem=5g
job.nExecutors=100
job.lookBackDays=2

type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${job.lookBackDays}"
dependencies=CheckTablesSLO
