job.name=AggFeaturesL3EC4
job.class=com.paytm.map.features.base.AggFeaturesL3EC4

job.nExecutors=50
job.executorMem=8g
job.driverMem=8g

type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${job.lookBackDays}"
dependencies=SalesPromoCategoryTable