job.name=CustomerDeviceFeatures
job.class=com.paytm.map.features.base.CustomerDeviceFeatures

job.nExecutors=50

type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${job.gaBackFillDays}"
dependencies=CheckTablesSLO
