job.name=gaAggTable
job.class=com.paytm.map.features.base.DFCache

job.nExecutors=100
job.memoryOverhead=10g

type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optCmds "--conf spark.yarn.executor.memoryOverhead=${job.memoryOverhead}" --optArgs "${job.lookBackDays} gaAggTable"
dependencies=CheckTablesSLO