job.name=InsuranceFeatures
job.class=com.paytm.map.features.base.InsuranceFeatures

type=command

job.nExecutors=24
job.executorMem=8g
job.executorCores=2
job.driverMem=8g

command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${job.lookBackDays}"

dependencies=SalesTable