job.name=OnlineFeatures
job.class=com.paytm.map.features.base.OnlineFeatures

job.nExecutors=50
job.lookBackDays=40

type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${job.lookBackDays}"
dependencies=PaytmFirstDroppedFeatures
