job.name=OverallFeatures
job.class=com.paytm.map.features.base.OverallFeatures

job.nExecutors=12
job.executorMem=2g

type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${job.lookBackDays}"
dependencies=AggFeaturesSMS
