job.name=PaymentFeatures
job.class=com.paytm.map.features.base.PaymentFeatures

job.nExecutors=50
job.lookBackDays=40

type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optCmds "--conf spark.yarn.executor.memoryOverhead=${job.memoryOverhead2G}" --optArgs "${job.lookBackDays}"
dependencies=PaymentsTable
