job.name=STRTable
job.class=com.paytm.map.features.base.DFCache

job.nExecutors=50
job.executorMem=8g
job.executorCores=4

type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${job.lookBackDays} strTable"
dependencies=CheckTablesSLO