job.name=FeatureValueIndiaTable
job.class=com.paytm.map.features.featurevalue.FeatureValueJob

type=command
job.driverMem=16g

command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv}  ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors}  ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optCmds "--conf spark.rpc.message.maxSize=768" --optArgs "${groupPrefix}"
dependencies=CheckFeaturesGroup1,CheckFeaturesGroup2,CheckFeaturesGroup3,CheckFeaturesGroup4