job.name=G3CreateGAL3EC2
job.class=com.paytm.map.features.Chakki.CreateDataSet
job.nExecutors=8
job.executorCores=8
job.executorMem=8g

type=command
levelPrefix=GAL3EC2

command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${levelPrefix} ${groupPrefix}"
dependencies=G3CreateGAL3EC3