job.name=G3CreatePushCampaigns
job.class=com.paytm.map.features.Chakki.CreateDataSet

job.nExecutors=50
job.executorMem=16g
job.executorCores=2

type=command
levelPrefix=PUSH
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${levelPrefix} ${groupPrefix}"
dependencies=G3CreateLastSeen
