job.name=G3CreateL1
job.class=com.paytm.map.features.Chakki.CreateDataSet

type=command
levelPrefix=PAYTM

job.nExecutors=60
job.executorMem=16g
job.executorCores=2

command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${levelPrefix} ${groupPrefix}"
dependencies=G3CheckL1Aggregates