job.name=MerchantSuperCashback
job.class=com.paytm.map.features.merchant.MerchantSuperCashback

job.nExecutors=24
job.executorMem=4g
job.executorCores=2

type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${job.lookBackDays}"
dependencies=UploadSpecs
