job.name=MerchantAggGAFeatures
job.class=com.paytm.map.features.merchant.MerchantAggGAFeatures

job.nExecutors=36
job.executorMem=2g
job.executorCores=2

type=command
command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${job.lookBackDays}"
dependencies=MerchantProfile