job.name=G2CreateGABK
job.class=com.paytm.map.features.Chakki.CreateDataSet
job.nExecutors=8
job.executorCores=8
job.executorMem=8g

type=command
levelPrefix=GABK

command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${levelPrefix} ${groupPrefix}"
dependencies=G2CreateL2EC