job.name=G2CreateSuperCashback
job.class=com.paytm.map.features.Chakki.CreateDataSet
job.nExecutors=50
job.executorMem=12g

type=command
levelPrefix=SCB

command=python ${baseDir}/bin/spark_native_submit.py ${flowEnv} ${job.targetDate} ${baseDir}/mapfeatures.jar ${job.class} ${job.name} ${job.driverMem} ${job.nExecutors} ${job.executorMem} ${job.executorCores} ${azkaban.job.attempt} ${retries} --optArgs "${levelPrefix} ${groupPrefix}"
dependencies=G2CreateSMSDataset